version: "3"

services:
  frontend:
    build: ./splash-dashboard
    ports:
      - "8050:8050"

  backend:
    build: ./splash-dashboard-backend
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: /data
        target: /data

  downloader:
    build: ./downloader
    volumes:
      - type: bind
        source: /data/data_inputs
        target: /data/data_inputs
